version: '3.4'

services:
  fuzzingbook:
    image: ortools-python-3.8
    container_name: my-ortools-python-3.8
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py"]
    ports:
      - 5678:5678
    volumes:
      - ./code:/app/code
