version: '3.4'

services:
  python-fuzzing-book:
    image: ortools-python-3.8
    container_name: my-ortools-python-3.8
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5678:5678
    volumes:
      - ./code:/app/code
    command: tail -f /dev/null # keep open container 
